### ISSUE TITLE
What to do after having the binaries?

### ISSUE THREAD

**Issue by 3rdxw** [upload-io/aws-image-magick-example#3] opened 2024-01-16 19:36 UTC
I succeed In making the binaries and I want to use them in my Amazon Lambda, How can I achieve that? 

what should I write in my lambda_function.py
BTW some binaries got 0KB size

```
import os

# Set MAGICK_HOME and LD_LIBRARY_PATH environment variables
os.environ['MAGICK_HOME'] = '/result'
os.environ['LD_LIBRARY_PATH'] = '/result'


from wand.image import Image
from wand.drawing import Drawing
from wand.color import Color
```
but I end up with error:
Unable to import module 'lambda_function': MagickWand shared library not found.
You probably had not installed ImageMagick library

**Comment by ljwagerfield** [comment] 2024-01-18 11:33
You're right (I think!) that the error is caused by the lack of the ImageMagick library being installed.

At present, we don't have any spare cycles to spend on resolving setup issues with this example, and for that I apologise 🙏 

Keep on plugging away at it: you'll get there eventually!!

**Closed as completed by ljwagerfield** 2024-01-18 11:33 UTC
